### ISSUE TITLE
Resizing the Browser Window Should Not Change the On/Off State of Grid

### ISSUE THREAD

**Issue by AlexisWalravens** [simanek/Heads-Up-Grid#5]
Hello,

Just to tell you that the grid shows up automatically when the window is resized.

That would be great if you can fixed that.

Thanks in advance.

**Comment by simanek** [comment]
Thanks for pointing out this shortcoming.

**Comment by simanek** [comment]
Thanks for submitting a issue/bug! You and another individual submitted 
the identical problem at almost the exact same time! I'll try to take a 
look this weekend while also getting reacquainted with Git/Github, which 
is long overdue.

Jason Simanek

**Comment by simanek** [comment]
Had to dig myself out of a bad merge, so the 4 commits above are actually just 2 commits done twice. Please download the latest versions of 
- example_responsive.html
- hugrid.js

I have added a new variable "gridstate" that records the current state of the grid (on or off). This makes it possible to preserve that state as the browser window is resized.

**Comment by simanek** [comment]
Hello,

I have just submitted a fix. Please take a look here:

https://github.com/simanek/Heads-Up-Grid/issues/5

and (in case you aren't familiar with Github – I'm still learning 
myself) you can download the new version here:

https://github.com/simanek/Heads-Up-Grid/downloads

The bug/issue page describes which files were changed. Let me know via 
email or comment on the Github issue directly if this update fixes the 
problem.

Jason Simanek

**Comment by simanek** [comment]
So the email reply I attempted to send ended up becoming a comment on this issue...  Is it obvious that I'm new to Github? :D

**Comment by AlexisWalravens** [comment]
Sorry for the time I took to reply.

It looks like it's fixed. :D

So, I just have to replace hugrid.js on my site to fix it ?

Thanks a lot for fixing that so quickly !

**Comment by simanek** [comment]
@Pix3lmate Yes, replace hugrid.js and review the example_responsive.html javascript in the head element. There's a new function referred to within the window.resize function.

**Comment by simanek** [comment]
This problem is successfully fixed!

**Comment by AlexisWalravens** [comment]
Thanks again ! I'm gonna use it in my new portfolio i'm working on ! :)
