### ISSUE TITLE
Rows not showing

### ISSUE THREAD

**Issue by sunilw** [simanek/Heads-Up-Grid#8]
Hi.

I'm using firefox and chrome in ubuntu.

Columns are showing, but not rows.

The rows show when I view the same pages in iBBdemo

**Comment by simanek** [comment]
Hello,

Do the rows appear on the main Heads-Up Grid site? http://bohemianalps.com/tools/grid/

I'm running Ubuntu 12.04 with Firefox 13.01 and Chromium 18.0.etc and the row lines are displaying fine. Perhaps I could help troubleshoot your specific project's settings?

**Comment by sunilw** [comment]
Hi simanek.

Thanks for the offer to troubleshoot. After cleaning up my own project, I can't replicate the issue. Must have been something on my end.
